In [ ]:
#Import libraries
import numpy as np

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [ ]:
#load dataset
data = load_diabetes()
X = data.data
y = data.target


In [ ]:
#convert target to binary (classification)
y_binary = (y > np.median(y)).astype(int)


In [ ]:
#train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_binary,
    test_size=0.2,
    random_state=42,
    stratify=y_binary
)


In [ ]:
# feature scaling (important)
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [ ]:
#model 1: K- nearest Neighbors (KNN)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

knn_pred = knn.predict(X_test_scaled)


In [ ]:
# Model 2 : Logistic Regression (liblinear)
lr_liblinear = LogisticRegression(solver="liblinear")
lr_liblinear.fit(X_train_scaled, y_train)

liblinear_pred = lr_liblinear.predict(X_test_scaled)


In [ ]:
# model 3 : logistic regression (lbfgs)
lr_lbfgs = LogisticRegression(
    solver="lbfgs",
    max_iter=1000
)
lr_lbfgs.fit(X_train_scaled, y_train)

lbfgs_pred = lr_lbfgs.predict(X_test_scaled)


In [ ]:
#model evaluation
def evaluate(name, y_true, y_pred):
    print(f"\n{name}")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
    print("Classification Report:\n", classification_report(y_true, y_pred))

evaluate("KNN", y_test, knn_pred)
evaluate("Logistic Regression (liblinear)", y_test, liblinear_pred)
evaluate("Logistic Regression (lbfgs)", y_test, lbfgs_pred)



KNN
Accuracy: 0.7528089887640449
Confusion Matrix:
 [[34 11]
 [11 33]]
Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.76      0.76        45
           1       0.75      0.75      0.75        44

    accuracy                           0.75        89
   macro avg       0.75      0.75      0.75        89
weighted avg       0.75      0.75      0.75        89


Logistic Regression (liblinear)
Accuracy: 0.7415730337078652
Confusion Matrix:
 [[31 14]
 [ 9 35]]
Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.69      0.73        45
           1       0.71      0.80      0.75        44

    accuracy                           0.74        89
   macro avg       0.74      0.74      0.74        89
weighted avg       0.74      0.74      0.74        89


Logistic Regression (lbfgs)
Accuracy: 0.7415730337078652
Confusion Matrix:
 [[31 14]
 [ 9 35]]
Classification Report:
       